runtime: python27
api_version: 1
threadsafe: true
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_instances: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index\.html
- url: /index\.html
  static_files: static/index.html
  upload: static/index\.html
- url: /success\.html
  static_files: static/success.html
  upload: static/success\.html
- url: /css
  static_dir: static/css
- url: /oauth2callback
  script: main.app
  login: required
- url: /privacy.html
  static_files: static/privacy.html
  upload: static/privacy\.html
- url: /googlef97e27405069776a.html
  static_files: static/googlef97e27405069776a.html
  upload: static/googlef97e27405069776a\.html
- url: /.*
  script: main.app
